// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

type Product struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Price       float64     `json:"price"`
	TaxRate     float64     `json:"taxRate"`
	Metadata    []byte      `json:"metadata"`
	CreatedAt   interface{} `json:"createdAt"`
	UpdatedAt   interface{} `json:"updatedAt"`
}
