// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: products.sql

package sqlc

import (
	"context"
)

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, tax_rate, metadata, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.TaxRate,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, description, price, tax_rate, metadata, created_at, updated_at
FROM products
WHERE name ILIKE '%' || $3::TEXT || '%'
  OR description ILIKE '%' || $3::TEXT || '%'
ORDER BY $4::TEXT
LIMIT $1
OFFSET $2
`

type GetProductsParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Query  string `json:"query"`
	Sortby string `json:"sortby"`
}

func (q *Queries) GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProducts,
		arg.Limit,
		arg.Offset,
		arg.Query,
		arg.Sortby,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.TaxRate,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsTotalCount = `-- name: GetProductsTotalCount :one
SELECT COUNT(*)
FROM products
WHERE name ILIKE '%' || $1::TEXT || '%'
  OR description ILIKE '%' || $1::TEXT || '%'
`

func (q *Queries) GetProductsTotalCount(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, getProductsTotalCount, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}
